"""add pickup location to requests

Revision ID: 6412e24b85a6
Revises: 0003_make_role_nullable
Create Date: 2026-06-17 16:15:00.603941
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6412e24b85a6'
down_revision: Union[str, None] = '0003_make_role_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_requests', sa.Column('pickup_location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation_requests', 'pickup_location')
    # ### end Alembic commands ###
